/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config dist/server/wrangler.json --include-runtime=false` (hash: c3ad596018f3e4e63b63ad074ac97d75)
interface __BaseEnv_Env {
	DASHBOARD_SNAPSHOTS: KVNamespace;
	LOGIN_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	DASHBOARD_USERNAME: string;
	DASHBOARD_PASSWORD: string;
	DASHBOARD_SESSION_SECRET: string;
	DASHBOARD_BD_ACCOUNTS: string;
	DASHBOARD_ADDITIONAL_ADMINS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DASHBOARD_USERNAME" | "DASHBOARD_PASSWORD" | "DASHBOARD_SESSION_SECRET" | "DASHBOARD_BD_ACCOUNTS" | "DASHBOARD_ADDITIONAL_ADMINS">> {}
}
