/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --config dist/server/wrangler.json worker-configuration.d.ts` (hash: 85f7750dfd61c55ab8526ee934a31e58)
interface __BaseEnv_Env {
	DASHBOARD_SNAPSHOTS: KVNamespace;
	LOGIN_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	DASHBOARD_USERNAME: string;
	DASHBOARD_PASSWORD: string;
	DASHBOARD_SESSION_SECRET: string;
	DASHBOARD_BD_ACCOUNTS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DASHBOARD_USERNAME" | "DASHBOARD_PASSWORD" | "DASHBOARD_SESSION_SECRET" | "DASHBOARD_BD_ACCOUNTS">> {}
}
