/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config dist/server/wrangler.json --include-runtime=false` (hash: 25d0567647a07ffd56a7b752ecbf3cd6)
interface __BaseEnv_Env {
	DASHBOARD_SNAPSHOTS: KVNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
