"use client";

import { useCallback, useEffect, useMemo, useState, useSyncExternalStore } from "react";
import Image from "next/image";
import { Activity, BarChart3, Download, LayoutDashboard, RefreshCw, RotateCcw, Search, UsersRound, Waypoints, Zap } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import dashboardData from "./dashboard-data.json";
import walletData from "./wallet-data.json";

type View = "总体" | "代理商" | "API";
type Lang = "zh" | "en";
type Platform = "business" | "wallet";
type Overall = { name:string; target:number; recharge:number; cards:number; yesterday:number };
type Detail = { name:string; owner:string; type:"代理商"|"API"; recharge:number; consumption:number; cards:number; yesterday:number };
type Report = { date:string; details:Omit<Detail,"yesterday">[] };
type Period = { id:string; label:string; start:string; end:string; overall:Overall[]; details:Detail[]; daily:Report[] };
const fallbackPeriods:Record<Platform,Period[]> = {
 business: dashboardData.periods as Period[],
 wallet: walletData.periods as Period[],
};
type DashboardPayload = { updatedAt?:string; business?:{periods?:Period[]}; wallet?:{periods?:Period[]} };
const colors = ["#58d2a5", "#49a6f2", "#59d4e8", "#9b79e8", "#75889a"];
const money = (v:number) => v >= 1e6 ? `${(v/1e6).toFixed(2)}M` : v >= 1e3 ? `${Math.round(v/1e3).toLocaleString()}K` : Math.round(v).toLocaleString();
const number = (v:number) => v.toLocaleString("en-US",{maximumFractionDigits:0});
const words = {
 zh:{title:"趋势洞察",sub:"数据驱动增长 · 洞察成就未来",dashboard:"看板概览",team:"BD 排名",entities:"代理 / API 排名",trends:"趋势分析",imported:"已导入每日数据",export:"导出日报",month:"月份",allPeriods:"全部历史",basis:"统计口径",mtd:"截至日期（月累计）",range:"起止日期（跨月周期）",asOf:"截至",start:"开始日期",end:"结束日期",reset:"重置筛选",bd:"BD",allBd:"全部BD",metric:"排名指标",recharge:"充值金额",completion:"完成率",dailyRecharge:"当日充值",averageDaily:"日均充值",search:"搜索 BD、代理商或 API",updated:"数据更新于",target:"月目标",cumulative:"累计充值",period:"周期充值",rate:"整体完成率",dailyNeed:"后续日均需完成",days:"周期天数",targetHint:"本月总目标",dateHint:"当前统计周期",cards:"开卡",cumulativeTrend:"累计充值趋势",actual:"实际累计充值",targetPace:"目标进度",contribution:"BD 贡献占比",daily:"每日充值金额",attention:"异常与关注",seeAll:"查看全部",ranking:"总体排名",overall:"总体",agents:"代理商",api:"API",rank:"排名",owner:"归属 BD",consumption:"累计消费",status:"状态",monthTotal:"月累计",periodRange:"周期",above:"超目标",onTrack:"进度正常",watch:"需关注",behind:"落后",none:"当前没有需要特别关注的 BD",source:"数据来源：UB每日数据.xlsx · 数据会跟随日期、BD 与类型筛选联动",gap:"预计缺口",compared:"较前一日",language:"EN"},
 en:{title:"Trend Intelligence",sub:"Data-driven growth · Insight for what comes next",dashboard:"Overview",team:"BD Ranking",entities:"Agent / API Ranking",trends:"Trend Analysis",imported:"Daily data imported",export:"Export report",month:"Month",allPeriods:"All history",basis:"Calculation basis",mtd:"As-of date (month-to-date)",range:"Date range (cross-month)",asOf:"As of",start:"Start date",end:"End date",reset:"Reset filters",bd:"BD",allBd:"All BDs",metric:"Ranking metric",recharge:"Recharge",completion:"Achievement rate",dailyRecharge:"Daily recharge",averageDaily:"Daily average",search:"Search BD, agent, or API",updated:"Updated",target:"Monthly target",cumulative:"Cumulative recharge",period:"Period recharge",rate:"Achievement rate",dailyNeed:"Required daily average",days:"Days in period",targetHint:"Total target this month",dateHint:"Current reporting period",cards:"Cards issued",cumulativeTrend:"Cumulative recharge trend",actual:"Actual recharge",targetPace:"Target pace",contribution:"BD contribution",daily:"Daily recharge",attention:"Anomalies & attention",seeAll:"View all",ranking:"Overall ranking",overall:"Overall",agents:"Agents",api:"API",rank:"Rank",owner:"Owner BD",consumption:"Consumption",status:"Status",monthTotal:"Month to date",periodRange:"Period",above:"Above target",onTrack:"On track",watch:"Needs attention",behind:"Behind",none:"No BDs need special attention right now",source:"Source: UB Daily Data.xlsx · Date, BD, and type filters are linked across the dashboard",gap:"Projected gap",compared:"vs previous day",language:"中文"}
} as const;

function Kpi({label,value,hint,icon,accent=false}:{label:string;value:string;hint:string;icon:React.ReactNode;accent?:boolean}){return <article className="kpi"><div><p>{label}</p><strong className={accent?"accent":""}>{value}</strong><span>{hint}</span></div><i>{icon}</i></article>}

export default function Home(){
 const initialPeriod=fallbackPeriods.business.at(-1)!;
 const [periodSets,setPeriodSets]=useState<Record<Platform,Period[]>>(fallbackPeriods);
 const [platform,setPlatform]=useState<Platform>("business"),[lang,setLang]=useState<Lang>("en"),[month,setMonth]=useState(initialPeriod.id),[mode,setMode]=useState<"mtd"|"range">("mtd"),[start,setStart]=useState(initialPeriod.start),[end,setEnd]=useState(initialPeriod.end),[owner,setOwner]=useState("全部BD"),[metric,setMetric]=useState("充值金额"),[view,setView]=useState<View>("总体"),[search,setSearch]=useState(""),[updatedAt,setUpdatedAt]=useState("2026-09-15 10:20"),[nav,setNav]=useState("dashboard"),[syncing,setSyncing]=useState(false);
 const mounted=useSyncExternalStore(()=>()=>{},()=>true,()=>false);
 const syncData=useCallback(async(nextPlatform:Platform=platform)=>{setSyncing(true);try{const response=await fetch(`/api/dashboard?platform=${nextPlatform}`,{cache:"no-store"});if(!response.ok)return;const payload=await response.json() as DashboardPayload;const business=payload.business?.periods,wallet=payload.wallet?.periods;if(!business?.length&&!wallet?.length)return;setPeriodSets(current=>({...current,...(business?.length?{business}:{}),...(wallet?.length?{wallet}:{})}));if(payload.updatedAt)setUpdatedAt(payload.updatedAt);}catch{}finally{setSyncing(false)}},[platform]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void syncData()},0);return()=>window.clearTimeout(timer)},[syncData]);
 useEffect(()=>{const fallbackLatest=fallbackPeriods[platform].at(-1)!,latest=periodSets[platform].at(-1)!;if(mode==="mtd"&&month===fallbackLatest.id&&start===fallbackLatest.start&&end===fallbackLatest.end&&latest.end!==end){setMonth(latest.id);setStart(latest.start);setEnd(latest.end)}},[periodSets,platform,mode,month,start,end]);
 const t=words[lang],periods=periodSets[platform],period=periods.find(p=>p.id===month)??periods.at(-1)!;
 const firstDate=periods.at(0)!.start,lastDate=periods.at(-1)!.end;
 const isWallet=platform==="wallet";
 const publicWalletBds=new Set(["victor","katrina","ruslan","mike","patrick","richard","upay"]);
 const displayedOwner=(rawOwner:string,name="")=>{
  if(!isWallet)return rawOwner;
  // Old snapshots may still contain internal employee or unassigned labels.
  // The public dashboard groups both under the single UPay ownership label.
  if(name.startsWith("UPay · "))return "UPay";
  return publicWalletBds.has(rawOwner.toLowerCase())?rawOwner:"UPay";
 };
 const updated=useMemo(()=>{const date=new Date(updatedAt);return Number.isNaN(date.getTime())?updatedAt:date.toLocaleString(lang==="zh"?"zh-CN":"en-GB",{hour12:false})},[updatedAt,lang]);
 const performanceLabel=isWallet?(lang==="zh"?"消费金额":"Consumption"):t.recharge;
 const cumulativeLabel=isWallet?(lang==="zh"?"累计消费":"Cumulative consumption"):t.cumulative;
 const periodLabel=isWallet?(lang==="zh"?"周期消费":"Period consumption"):t.period;
 const dailyLabel=isWallet?(lang==="zh"?"当日消费":"Daily consumption"):t.dailyRecharge;
 const averageDailyLabel=isWallet?(lang==="zh"?"日均消费":"Average daily consumption"):t.averageDaily;
 const availableViews:View[]=isWallet?["总体","代理商"]:["总体","代理商","API"];
 const countDays=(from:string,to:string)=>Math.max(0,Math.floor((new Date(`${to}T00:00:00`).getTime()-new Date(`${from}T00:00:00`).getTime())/86400000)+1);
 const reports=useMemo(()=>{const source=mode==="range"?periods.flatMap(p=>p.daily):period.daily;const from=mode==="range"?start:period.start;return source.filter(r=>r.date>=from&&r.date<=end)},[periods,period,start,end,mode]);
 const details=useMemo(()=>{if(mode==="mtd"&&end===period.end)return period.details;const map=new Map<string,Detail>();reports.forEach(r=>r.details.forEach(x=>{const k=`${x.owner}|${x.type}|${x.name}`,a=map.get(k)??{...x,recharge:0,consumption:0,cards:0,yesterday:0};a.recharge+=x.recharge;a.consumption+=x.consumption;a.cards+=x.cards;map.set(k,a)}));const last=new Map((reports.at(-1)?.details??[]).map(x=>[`${x.owner}|${x.type}|${x.name}`,x.recharge]));return [...map].map(([k,x])=>({...x,yesterday:mode==="mtd"?last.get(k)??0:x.recharge/Math.max(reports.length,1)}))},[period,reports,mode,end]);
 const allOverall=useMemo(()=>{if(mode==="mtd"&&end===period.end)return period.overall;const from=mode==="range"?start:period.start;const grouped=new Map<string,Overall>();periods.forEach(p=>{const overlapStart=from>p.start?from:p.start,overlapEnd=end<p.end?end:p.end;if(overlapStart>overlapEnd)return;const fullDays=countDays(p.start,p.end),coverage=countDays(overlapStart,overlapEnd)/fullDays;p.overall.forEach(x=>{const key=x.name.toLowerCase(),current=grouped.get(key)??{name:x.name,target:0,recharge:0,cards:0,yesterday:0};current.target+=x.target*coverage;grouped.set(key,current)})});const fallback=[...grouped.values()].find(x=>x.name.toLowerCase()==="others");details.forEach(x=>{const current=grouped.get(x.owner.toLowerCase())??fallback;if(current){current.recharge+=x.recharge;current.cards+=x.cards;current.yesterday+=x.yesterday}});return [...grouped.values()]},[periods,period,details,mode,start,end]);
 const displayedOverall=useMemo(()=>{if(!isWallet)return allOverall;const grouped=new Map<string,Overall>();allOverall.forEach(x=>{const name=displayedOwner(x.name),current=grouped.get(name)??{name,target:0,recharge:0,cards:0,yesterday:0};current.target+=x.target;current.recharge+=x.recharge;current.cards+=x.cards;current.yesterday+=x.yesterday;grouped.set(name,current)});return [...grouped.values()]},[allOverall,isWallet]);
 const bds=useMemo(()=>[...new Set([...displayedOverall.map(x=>x.name),...details.map(x=>displayedOwner(x.owner,x.name))])].sort(),[displayedOverall,details]);
 const overall=displayedOverall.filter(x=>owner==="全部BD"||x.name.toLowerCase()===owner.toLowerCase());
 const ownerMatches=(rawOwner:string,name="")=>owner==="全部BD"||displayedOwner(rawOwner,name).toLowerCase()===owner.toLowerCase();
 const source=view==="总体"?overall.map(x=>({...x,owner:x.name,consumption:0})):details.filter(x=>x.type===view&&ownerMatches(x.owner,x.name));
 const rows=[...source].filter(x=>`${x.name} ${displayedOwner(x.owner,x.name)}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>metric==="完成率"?b.recharge/(("target" in b&&b.target)||1)-a.recharge/(("target" in a&&a.target)||1):metric==="当日充值"?b.yesterday-a.yesterday:b.recharge-a.recharge);
 const target=overall.reduce((s,x)=>s+x.target,0),recharge=overall.reduce((s,x)=>s+x.recharge,0),cards=overall.reduce((s,x)=>s+x.cards,0),yesterday=overall.reduce((s,x)=>s+x.yesterday,0),elapsed=mode==="range"?countDays(start,end):countDays(period.start,end),totalDays=mode==="range"?countDays(start,end):new Date(+period.id.slice(0,4),+period.id.slice(5),0).getDate();
 const totals={target,recharge,cards,yesterday,rate:target?recharge/target:0,dailyNeed:Math.max(target-recharge,0)/Math.max(totalDays-elapsed,1),elapsed,totalDays};
 const daily=reports.map(r=>({date:r.date.slice(5).replace("-","/"),amount:r.details.filter(x=>ownerMatches(x.owner,x.name)).reduce((s,x)=>s+x.recharge,0)}));
 const trend=daily.map((x,i)=>({...x,actual:daily.slice(0,i+1).reduce((sum,row)=>sum+row.amount,0),target:totals.target*(i+1)/totals.totalDays}));
 const contribution=[...overall].sort((a,b)=>b.recharge-a.recharge).map(x=>({...x,share:totals.recharge?x.recharge/totals.recharge:0}));
 const attention=[...overall].filter(x=>x.target&&x.recharge/x.target<.7).sort((a,b)=>a.recharge/a.target-b.recharge/b.target).slice(0,5);
 const monthLabel=mode==="range"?`${start} — ${end}`:(lang==="zh"?period.label:new Intl.DateTimeFormat("en-US",{year:"numeric",month:"long"}).format(new Date(`${period.id}-01T00:00:00`)));
 const tip={background:"#0c1c1f",border:"1px solid #203638",borderRadius:8,color:"#e8f5f1"};
 const go=(id:string,v?:View)=>{setNav(id);if(v)setView(v);document.getElementById(id==="dashboard"?"top":id==="trends"?"trend":"ranking")?.scrollIntoView({behavior:"smooth"})};
 const switchMonth=(id:string)=>{if(id==="all"){setMonth("all");setMode("range");setStart(firstDate);setEnd(lastDate);setOwner("全部BD");return}const next=periods.find(p=>p.id===id)!;setMonth(id);setStart(next.start);setEnd(next.end);setOwner("全部BD")};
 const switchMode=(nextMode:"mtd"|"range")=>{if(nextMode==="range"){setMode("range");setMonth("all");setStart(firstDate);setEnd(lastDate);return}const latest=periods.at(-1)!;setMode("mtd");setMonth(latest.id);setStart(latest.start);setEnd(latest.end)};
 const resetFilters=()=>{const latest=periods.at(-1)!;setMonth(latest.id);setMode("mtd");setStart(latest.start);setEnd(latest.end);setOwner("全部BD");setMetric("充值金额");setSearch("");setView("总体")};
 const switchPlatform=(nextPlatform:Platform)=>{const next=periodSets[nextPlatform].at(-1)!;if(nextPlatform==="wallet")setSyncing(true);setPlatform(nextPlatform);setMonth(next.id);setMode("mtd");setStart(next.start);setEnd(next.end);setOwner("全部BD");setMetric("充值金额");setView("总体");setSearch("")};
 const state=(rate?:number)=>!rate?[t.behind,"red"]:rate>=1?[t.above,"green"]:rate>=.7?[t.onTrack,"blue"]:rate>=.43?[t.watch,"amber"]:[t.behind,"red"];
 return <main className="dashboard-shell" id="top"><aside className="side-nav"><div className="brand"><Image src="/upay-logo.png" alt="UPay" width={31} height={31}/><strong>UPay</strong></div><p className="nav-caption">{lang==="zh"?"快速定位":"QUICK JUMP"}</p><nav><button className={`nav-link ${nav==="dashboard"?"active":""}`} onClick={()=>go("dashboard","总体")}><LayoutDashboard size={18}/>{t.dashboard}</button><button className={`nav-link ${nav==="team"?"active":""}`} onClick={()=>go("team","总体")}><UsersRound size={18}/>{t.team}</button><button className={`nav-link ${nav==="entities"?"active":""}`} onClick={()=>go("entities","代理商")}><Waypoints size={18}/>{isWallet?(lang==="zh"?"代理商排名":"Agent ranking"):t.entities}</button><button className={`nav-link ${nav==="trends"?"active":""}`} onClick={()=>go("trends")}><BarChart3 size={18}/>{t.trends}</button></nav><div className="nav-footer"><span/>{t.imported}</div></aside>
 <div className="workspace"><header className="topbar"><div className="title-block"><p className="eyebrow">UP OPERATIONS · {isWallet?"UPAY WALLET":"UP BUSINESS"}</p><h1><em>{lang==="zh"?"趋势":"Trend"}</em> {lang==="zh"?"洞察":"Intelligence"}</h1><p className="subtitle">{t.sub}</p></div><div className="topbar-actions"><div className="platform-switch" aria-label={lang==="zh"?"平台切换":"Platform switch"}><button className={!isWallet?"selected":""} onClick={()=>switchPlatform("business")}>UP Business</button><button className={isWallet?"selected":""} onClick={()=>switchPlatform("wallet")}>UPay Wallet</button></div><button className="language-button" aria-label={lang==="zh"?"切换为英文":"Switch to Chinese"} onClick={()=>setLang(lang==="zh"?"en":"zh")}>{t.language}</button><button className="icon-button" aria-label={lang==="zh"?"刷新数据":"Refresh dashboard data"} onClick={()=>void syncData()} disabled={syncing}><RefreshCw size={17} className={syncing?"spin":""}/></button><button className="export-button" onClick={()=>window.print()}><Download size={17}/><span>{t.export}</span></button></div></header>
 <section className="control-row"><div className="filter-controls"><label><span>{t.month}</span><select value={month} onChange={e=>switchMonth(e.target.value)}><option value="all">{t.allPeriods}</option>{periods.map(p=><option key={p.id} value={p.id}>{lang==="zh"?p.label:new Intl.DateTimeFormat("en-US",{year:"numeric",month:"long"}).format(new Date(`${p.id}-01T00:00:00`))}</option>)}</select></label><label><span>{t.basis}</span><select value={mode} onChange={e=>switchMode(e.target.value as "mtd"|"range")}><option value="mtd">{t.mtd}</option><option value="range">{t.range}</option></select></label>{mode==="range"&&<div className="date-range-fields"><label><span>{t.start}</span><input type="date" value={start} min={firstDate} max={end} onChange={e=>setStart(e.target.value)}/></label><span className="date-divider">→</span><label><span>{t.end}</span><input type="date" value={end} min={start} max={lastDate} onChange={e=>setEnd(e.target.value)}/></label></div>}{mode==="mtd"&&<label><span>{t.asOf}</span><input type="date" value={end} min={period.start} max={period.end} onChange={e=>setEnd(e.target.value)}/></label>}<label><span>{t.bd}</span><select value={owner} onChange={e=>setOwner(e.target.value)}><option value="全部BD">{t.allBd}</option>{bds.map(x=><option key={x}>{x}</option>)}</select></label><label><span>{t.metric}</span><select value={metric} onChange={e=>setMetric(e.target.value)}><option value="充值金额">{performanceLabel}</option><option value="完成率">{t.completion}</option><option value="当日充值">{mode==="mtd"?dailyLabel:averageDailyLabel}</option></select></label></div><div className="filter-utilities"><div className="filter-actions"><button className="reset-button" onClick={resetFilters}><RotateCcw size={14}/>{t.reset}</button><div className="search-box"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={isWallet?(lang==="zh"?"搜索 BD 或代理商":"Search BD or agent"):t.search}/></div></div><small>{t.updated} {updated}</small></div></section>
 {syncing&&isWallet&&<div className="wallet-sync-notice" role="status"><RefreshCw size={16} className="spin"/><span>{lang==="zh"?"正在读取最新 UPay Wallet 数据，请稍候（首次约需 1 分钟）":"Fetching the latest UPay Wallet data — first load can take about 1 minute."}</span></div>}
 <section className="kpi-strip"><Kpi label={t.target} value={money(totals.target)} hint={mode==="range"?`${monthLabel} · ${t.dateHint}`:`${monthLabel} · ${t.targetHint}`} icon={<Activity size={19}/>}/><Kpi label={mode==="mtd"?cumulativeLabel:periodLabel} value={money(totals.recharge)} hint={`${t.asOf} ${end}`} icon={<BarChart3 size={19}/>}/><Kpi label={t.rate} value={`${(totals.rate*100).toFixed(1)}%`} hint={isWallet?`${t.asOf} ${end}`:`${t.cards} ${number(totals.cards)}`} icon={<Activity size={19}/>} accent/><Kpi label={mode==="mtd"?t.dailyNeed:t.days} value={mode==="mtd"?money(totals.dailyNeed):String(reports.length)} hint={mode==="mtd"?`${totals.totalDays-totals.elapsed} ${lang==="zh"?"天后截止":"days remaining"}`:t.dateHint} icon={<Zap size={19}/>}/></section>
 <section className="analytics-grid" id="trend"><article className="chart-panel trend-chart"><header><div><p className="eyebrow">PERFORMANCE TREND</p><h2>{isWallet?(lang==="zh"?"累计消费趋势":"Cumulative consumption trend"):t.cumulativeTrend}</h2></div><div className="legend"><span className="actual">{isWallet?(lang==="zh"?"实际累计消费":"Actual consumption"):t.actual}</span><span className="pace">{t.targetPace}</span></div></header><div className="chart-body">{mounted&&<ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={0}><AreaChart data={trend}><CartesianGrid stroke="#173033" vertical={false}/><XAxis dataKey="date" stroke="#71898a" fontSize={11} tickLine={false}/><YAxis stroke="#71898a" fontSize={11} tickLine={false} axisLine={false} tickFormatter={v=>`${(v/1e6).toFixed(0)}M`}/><Tooltip contentStyle={tip} formatter={v=>money(Number(v))}/><Area type="monotone" dataKey="target" stroke="#a9bab7" fill="transparent" strokeDasharray="5 5" strokeWidth={2}/><Area type="monotone" dataKey="actual" stroke="#58d2a5" fill="#143b35" strokeWidth={3}/></AreaChart></ResponsiveContainer>}</div><footer><span>{t.target} <b>{money(totals.target)}</b></span><span>{t.gap} <b className={totals.target>totals.recharge?"negative":"positive"}>{money(Math.max(totals.target-totals.recharge,0))}</b></span></footer></article>
 <article className="chart-panel contribution"><header><div><p className="eyebrow">CONTRIBUTION</p><h2>{t.contribution}</h2></div></header><div className="contribution-body"><div className="donut-wrap">{mounted&&<ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={0}><PieChart><Pie data={contribution} dataKey="recharge" nameKey="name" innerRadius={48} outerRadius={73} paddingAngle={1} stroke="none">{contribution.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={tip} formatter={v=>money(Number(v))}/></PieChart></ResponsiveContainer>}<div><strong>{money(totals.recharge)}</strong><span>{cumulativeLabel}</span></div></div><div className="contribution-list">{contribution.slice(0,5).map((x,i)=><p key={x.name}><i style={{background:colors[i%colors.length]}}/><b>{x.name}</b><span>{(x.share*100).toFixed(1)}%</span><em>{money(x.recharge)}</em></p>)}</div></div></article>
 <article className="chart-panel daily-chart"><header><div><p className="eyebrow">DAILY VELOCITY</p><h2>{isWallet?(lang==="zh"?"每日消费金额":"Daily consumption"):t.daily}</h2></div><div className="daily-summary"><strong>{money(totals.yesterday)}</strong><span>{t.compared}</span></div></header><div className="chart-body">{mounted&&<ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={0}><BarChart data={daily}><CartesianGrid stroke="#173033" vertical={false}/><XAxis dataKey="date" stroke="#71898a" fontSize={11} tickLine={false}/><YAxis stroke="#71898a" fontSize={11} tickLine={false} axisLine={false} tickFormatter={v=>`${Math.round(v/1000)}K`}/><Tooltip contentStyle={tip} formatter={v=>money(Number(v))}/><Bar dataKey="amount" fill="#58d2a5" radius={[2,2,0,0]}/></BarChart></ResponsiveContainer>}</div></article>
 <article className="attention-panel"><header><div><p className="eyebrow">ACTION QUEUE</p><h2>{t.attention}</h2></div><button onClick={()=>go("team","总体")}>{t.seeAll} →</button></header><div className="attention-list">{attention.length?attention.map((x,i)=><button key={x.name} onClick={()=>{setSearch(x.name);go("team","总体")}}><i className={i<2?"high":"medium"}>!</i><span><b>{x.name}</b><small>{lang==="zh"?`月度进度仅 ${(x.recharge/x.target*100).toFixed(1)}%`:`Monthly progress is ${(x.recharge/x.target*100).toFixed(1)}%`}</small></span><time>{end}</time></button>):<p className="empty-note">{t.none}</p>}</div></article></section>
 <section className="ranking-panel" id="ranking"><header><div><p className="eyebrow">LEADERBOARD</p><h2>{t.ranking}</h2></div><div className="view-tabs">{availableViews.map(x=><button key={x} className={view===x?"selected":""} onClick={()=>setView(x)}>{x==="总体"?t.overall:x==="代理商"?t.agents:t.api}</button>)}</div></header><div className="table-wrap"><table><thead><tr><th>{t.rank}</th><th>{view==="总体"?"BD":view==="代理商"?t.agents:t.api}</th><th>{t.owner}</th>{view==="总体"?<><th>{t.target}</th><th>{mode==="mtd"?cumulativeLabel:periodLabel}</th><th>{t.completion}</th></>:isWallet?<th>{mode==="mtd"?cumulativeLabel:periodLabel}</th>:<><th>{mode==="mtd"?cumulativeLabel:periodLabel}</th><th>{t.consumption}</th><th>{mode==="mtd"?t.monthTotal:t.periodRange}</th></>}<th>{mode==="mtd"?dailyLabel:averageDailyLabel}</th><th>{t.cards}</th><th>{t.status}</th></tr></thead><tbody>{rows.map((row,i)=>{const rate=view==="总体"&&"target" in row&&row.target?row.recharge/row.target:undefined,[label,tone]=state(rate);return <tr key={`${row.name}-${row.owner}`}><td><span className={`rank ${i<3?"top":""}`}>{i+1}</span></td><td className="name-cell"><i>{row.name[0]?.toUpperCase()}</i><b>{row.name}</b></td><td>{displayedOwner(row.owner,row.name)}</td>{view==="总体"&&"target" in row?<><td>{money(row.target)}</td><td className="money">{money(row.recharge)}</td><td><div className="rate-cell"><b>{(rate!*100).toFixed(1)}%</b><span><i style={{width:`${Math.min(rate!*100,100)}%`}}/></span></div></td></>:isWallet?<td className="money">{money(row.recharge)}</td>:<><td className="money">{money(row.recharge)}</td><td>{money(row.consumption)}</td><td>{mode==="mtd"?t.monthTotal:`${start} — ${end}`}</td></>}<td>{money(row.yesterday)}</td><td>{number(row.cards)}</td><td><span className={`status ${tone}`}>{label}</span></td></tr>})}</tbody></table></div></section><p className="data-note">{isWallet?(lang==="zh"?"数据来源：UW每日数据.xlsx · 业绩口径为消费金额，日期、BD 与代理商筛选联动":"Source: UW Daily Data.xlsx · Performance is measured by consumption; date, BD, and agent filters are linked"):t.source}</p></div></main>
}
