import { privateResponse } from "./site-access";

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);
}

export function bdPage(owner: string): Response {
  const safeOwner = escapeHtml(owner);
  return privateResponse(new Response(`<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow">
<title>UPay · ${safeOwner}</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#e5f1ee;background:#071719;color-scheme:dark}
*{box-sizing:border-box}body{margin:0}button,select,input{font:inherit}button{cursor:pointer}header{border-bottom:1px solid #1a3736;background:#091b1d;position:sticky;top:0;z-index:1}
.header-inner{max-width:1250px;margin:auto;padding:18px 28px;display:flex;align-items:center;justify-content:space-between;gap:18px}.brand{display:flex;align-items:center;gap:12px;font-weight:750;font-size:21px}.brand img{width:35px;height:35px;object-fit:contain}.header-actions{display:flex;gap:10px;align-items:center}.header-actions button,.header-actions select,.filters select,.filters input{background:#0b2324;border:1px solid #294b48;color:#dcefeb;border-radius:9px;padding:10px 13px}.header-actions form{margin:0}.header-actions .selected,.header-actions .accent{background:#56d2ab;color:#06251c;border-color:#56d2ab}
main{max-width:1250px;margin:auto;padding:30px 28px 60px}.eyebrow{font-size:11px;letter-spacing:.16em;color:#779b97;font-weight:700;text-transform:uppercase;margin:0 0 7px}h1{font-size:29px;font-weight:630;margin:0}#subtitle{margin:8px 0 0;color:#8daaa5;font-size:14px}.filters{display:flex;gap:10px;flex-wrap:wrap;margin:27px 0 20px}.filters select,.filters input{min-height:41px}.filters input{min-width:240px}.kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.kpi,.panel{border:1px solid #21403e;border-radius:12px;background:#0a2022}.kpi{padding:21px}.kpi span{display:block;color:#88a7a2;font-size:12px;margin-bottom:10px}.kpi strong{font-size:25px;letter-spacing:-.03em}.kpi:first-child strong{color:#61d8b0}.grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(310px,1fr);gap:14px;margin-top:14px}.panel{overflow:hidden}.panel h2{font-weight:550;font-size:17px;margin:0;padding:19px 20px;border-bottom:1px solid #1d3837}.chart{height:235px;padding:15px 18px 14px;display:flex;align-items:end;gap:4px;overflow-x:auto}.bar-wrap{height:100%;flex:1;min-width:8px;display:flex;align-items:end}.bar{width:100%;background:#59d3a9;border-radius:3px 3px 0 0;min-height:2px;opacity:.88}.chart-caption{color:#799a96;font-size:12px;padding:0 19px 15px}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;min-width:650px}th{text-align:left;color:#819e9b;font-size:11px;font-weight:650}td{font-size:13px;color:#c6d8d4}th,td{padding:14px 16px;border-bottom:1px solid #1b3534}tbody tr:hover{background:#112a2c}.name{color:#e9f5f1;font-weight:650}.empty{padding:36px 20px;color:#8ca9a4}.loading{min-height:80px;color:#9fbbb6;padding:26px 0}#error{color:#ffaea1}a{color:#78ddbd}footer{padding-top:24px;color:#6d928c;font-size:12px}
@media(max-width:800px){.header-inner{flex-wrap:wrap}.header-actions{flex-wrap:wrap}.kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.grid{grid-template-columns:1fr}}@media(max-width:500px){main{padding:22px 15px 40px}.header-inner{padding:14px 15px}.kpi{padding:14px}.kpi strong{font-size:20px}.filters>*{flex:1}.filters input{min-width:0}}
</style></head><body>
<header><div class="header-inner"><div class="brand"><img src="/upay-logo.png" alt="UPay">UPay</div><div class="header-actions"><button id="business" class="selected" type="button">UP Business</button><button id="wallet" type="button">UPay Wallet</button><button id="language" type="button">中文</button><button id="export" type="button" class="accent">Export report</button><form method="post" action="/access/logout"><button type="submit" id="signout">Sign out</button></form></div></div></header>
<main><p class="eyebrow" id="eyebrow">BD dashboard · STAGING</p><h1 id="title">${safeOwner}</h1><p id="subtitle">Your own performance, agents and API clients</p>
<div class="filters"><select id="month" aria-label="Month"></select><input id="search" type="search" placeholder="Search your agents and API clients" aria-label="Search agents"></div>
<div id="message" class="loading" role="status">Loading your data…</div>
<div id="content" hidden><div class="kpis"><div class="kpi"><span id="value-label">Total amount</span><strong id="total">—</strong></div><div class="kpi"><span id="target-label">Monthly target</span><strong id="target">—</strong></div><div class="kpi"><span id="rate-label">Achievement</span><strong id="rate">—</strong></div><div class="kpi"><span id="cards-label">Cards issued</span><strong id="cards">—</strong></div></div>
<div class="grid"><section class="panel"><h2 id="trend-label">Daily trend</h2><div id="chart" class="chart"></div><div id="chart-caption" class="chart-caption"></div></section><section class="panel"><h2 id="agents-label">Agents and API clients</h2><div class="table-wrap"><table><thead><tr><th id="col-name">Name</th><th id="col-type">Type</th><th id="col-amount">Amount</th><th id="col-email">Email</th><th id="col-since">Cooperation since</th></tr></thead><tbody id="rows"></tbody></table></div></section></div><footer id="asof"></footer></div>
</main><script src="/bd-dashboard.js" defer></script></body></html>`, { headers: {
    "Content-Type": "text/html; charset=utf-8",
    "Content-Security-Policy": "default-src 'none'; img-src 'self'; script-src 'self'; connect-src 'self'; style-src 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'",
  } }));
}
